"""init models

Revision ID: e5a865aa0701
Revises: 
Create Date: 2026-01-16 17:48:55.631287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a865aa0701'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codeforces_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contests_codeforces_id'), 'contests', ['codeforces_id'], unique=True)
    op.create_index(op.f('ix_contests_id'), 'contests', ['id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codeforces_id', sa.String(length=20), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('solved_count', sa.BigInteger(), nullable=True),
    sa.Column('index', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_codeforces_id'), 'problems', ['codeforces_id'], unique=True)
    op.create_index(op.f('ix_problems_contest_id'), 'problems', ['contest_id'], unique=False)
    op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    op.create_index('ix_problems_rating_nonnull', 'problems', ['rating'], unique=False, postgresql_where=sa.text('rating IS NOT NULL'))
    op.create_table('problem_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_tags_id'), 'problem_tags', ['id'], unique=False)
    op.create_index(op.f('ix_problem_tags_problem_id'), 'problem_tags', ['problem_id'], unique=False)
    op.create_index(op.f('ix_problem_tags_tag'), 'problem_tags', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_tags_tag'), table_name='problem_tags')
    op.drop_index(op.f('ix_problem_tags_problem_id'), table_name='problem_tags')
    op.drop_index(op.f('ix_problem_tags_id'), table_name='problem_tags')
    op.drop_table('problem_tags')
    op.drop_index('ix_problems_rating_nonnull', table_name='problems', postgresql_where=sa.text('rating IS NOT NULL'))
    op.drop_index(op.f('ix_problems_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_contest_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_codeforces_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_contests_id'), table_name='contests')
    op.drop_index(op.f('ix_contests_codeforces_id'), table_name='contests')
    op.drop_table('contests')
    # ### end Alembic commands ###
